import sys
import time

print("[Config] Initializing DATA3.util.logging...")
time.sleep(0.6)
print("[WARNING] DATA3.util.logging.FileHandler: Memory leak detected in stream handler.")
time.sleep(0.4)
print("[SEVERE] NullPointerException at DATA3.util.logging.LogManager.readConfiguration")
time.sleep(0.8)
print("[INFO] Fallback to console stream. Dumping payload fragments:\n")
time.sleep(0.5)

cipher = (
    "JJFEERSHKUZEER2VLJKUKVBSJZFUMRCWI5GTEU2JIZDVMRKVJNMUSVK2IRDVIMS"
    "OJNNE4RSRKIZFATCKIFKTIUKTKRFU4QKWKNLEGR2KKUZFMQ2WLJKUURSDIZFVIU"
    "SVJNDEKRKLK5JU2SKKJBDEKVSLLFFVMTSFKVKDERSJJJBVKT2TGJFESUSNIUZFE"
    "UZSJNHECVCFKRBVASKWIJCEKURSKJGEURSFINKEUVSLGVCFITKNLJKEUWSFIUZFK"
    "S2IJNDE4RKVKFFU4SSKJJLE6VBSLJFFESCVJNIVEU2JGQZUKU2SINEEUWJSKZKVE"
    "MSMI5IVUVKNKRFVMTCCIJKUGVJSIVEVUQ2VIVGTEWCJJUZEMVKRJNHUWSSNIZHVE"
    "WSTI5HEIRJSKVFVESJVIJKEWTJSINFUEQ2UJNKTEQSHJJBUKTKSJNBUWTSEKZDVO"
    "U2DJFDEQRSVK5BVSSSGIVKUSV2DJZEVUTKFKFJUWSSJKJFVKNCOINJEUQSIKZJV"
    "IQ2LJI2USVSRKEZEES2OINCU2USLINFTKTCUJVHEWVKJLJDVMQ2VJNEUURK2KRDV"
    "OQ2OJFNE4RKPKNFUUSKSJNKTIUKTKRFU4QKUI5JEGS2KKUZFMS2TINFEUUSCIVB"
    "VKQ2HJNHE2RKTKNFUKS2SI5KU2TJSKREUKWSUI5KDET2LJEZEMR2RJMZESUSMIU3"
    "FIUSTJFGTERKTKEZEUSSGJNLEGUSLJZFUURSVGJJTEUSLIZCEKNSVGJCESSSGKZB"
    "VKS2GJNDEURKVKFFUWSKKIFLEWU2LJJEU4SCVKNLFGTKJKZDFMS2VKNBEUTJSKVF"
    "VMU2IJNHEEVKNKNFVES2GIRCVGVSDGJEUMRKWKVITEVSKJZFUKRKRKNDESSSDKVF"
    "VGMSKJFHE2RKTKJJUSSK2IVLEKUZSIZEVMQSFK5JEUV2KIZBFKMSTKNDUUUSDKVL"
    "VIQ2DJFDEKVKVKMZFOSSGIVKUOUSDJNDVMRSWJNLUWU2JJJAVKV2VKNCEWVSNKZE"
    "VCU2CJJFE4RKRKUZEES2RLJCTMU2LKZFUMSSVINKTERCJLJBVKRKTKNDEUTSLIVL"
    "VCU2LJFNEKRKLKMZFGSKKIFKVOVCTIZFVMTKWIVJTEUCKJZEVMQ2SKNGEWUSKKZF"
    "VGU2HJE2UEVKDKZJUISSGIVLEWVKLIZFUMS2EIVLFGTCKIZEVKS2OKNJUWSSBKVK"
    "VMU2EJNNEGVSLKUZEWSSKJRCUOVSKKVFVUQSFINJUWR2KJJCEKS2VGJGEWNKFKZG"
    "VCMSEJFGTMVBSKBEUW==="
)

chunk_size = 64
for i in range(0, len(cipher), chunk_size):
  chunk = cipher[i : i + chunk_size]
  sys.stdout.write(f"[Chunk {i // chunk_size + 1}] {chunk}\n")
  sys.stdout.flush()
  time.sleep(0.3) 
